import { AppTheme } from "./themeTypes";

const spacing = {
  xs: 6,
  sm: 10,
  md: 16,
  lg: 20,
  xl: 28,
} as const;

const radii = {
  sm: 10,
  md: 16,
  lg: 24,
  pill: 999,
} as const;

export const lightTheme: AppTheme = {
  dark: false,
  colors: {
    background: "#F7F2EA",
    backgroundMuted: "#F0E6D9",
    card: "#FFFDF8",
    cardMuted: "#F0E6D9",
    cardElevated: "#FFF7EF",
    input: "#FFFFFF",
    textPrimary: "#2B241F",
    textSecondary: "#5B4E43",
    textMuted: "#7A6E63",
    textOnAccent: "#FFF8F3",
    textOnDanger: "#FFF8F3",
    textOnInverse: "#FFFDF8",
    border: "#E0D4C5",
    borderSoft: "#EDE3D8",
    divider: "#D8CABA",
    accent: "#C56A4A",
    accentSoft: "#E7B5A4",
    accentMuted: "#F6DED5",
    success: "#4F7B59",
    successSoft: "#D6E4D1",
    warning: "#B97A2A",
    warningSoft: "#FFF2E2",
    error: "#B24A3B",
    errorSoft: "#FBEAE8",
    info: "#6E7FA8",
    infoSoft: "#F6EFE5",
    overlay: "rgba(43, 36, 31, 0.08)",
    backdrop: "rgba(43, 36, 31, 0.35)",
    shadow: "#2B241F",
    focusRing: "#2B241F",
    toastBackground: "#2B241F",
    toastBorder: "rgba(255,255,255,0.4)",
    liveChip: "#E4F1EB",
    cachedChip: "#ECE7F8",
    mockChip: "#FFF1E6",
    demoChip: "#F1ECE4",
    yarnOutline: "rgba(255,255,255,0.34)",
    inputPlaceholder: "#7A6E63",
  },
  spacing,
  radii,
  shadows: {
    card: {
      shadowColor: "#2B241F",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.06,
      shadowRadius: 20,
      elevation: 2,
    },
    floating: {
      shadowColor: "#2B241F",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 4,
    },
  },
  statusBarStyle: "dark",
};
